---
all:
  children:
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_port: 5985
        ansible_winrm_transport: ntlm
        ansible_user: "" #REPLACE
        ansible_password: "" #REPLACE
        scripts_path: "" #REPLACE
        scripts_ansible_location: "/BlueTeamTools/Windows-Scripts"
      children:
        dc:
          vars:
            scored_services: "dnsio, ldapio"
            is_win_server: "true"
            server_type: "dc"
            is_server_core: "false"
          hosts:
            10.14.1.1:
        web:
          vars:
            scored_services: "httpio, rdpio"
            is_win_server: "true"
            server_type: "web"
            is_server_core: "false"
          hosts:
            192.168.14.1:
        ngnix:
          vars:
            scored_services: "httpsio"
            is_win_server: "true"
            server_type: "web"
            is_server_core: "false"
          hosts:
            10.14.1.2:
        win10client:
          vars:
            scored_services: "winrmio, rdpio"
            is_win_server: "false"
            server_type: "null"
            is_server_core: "false"
          hosts:
            10.14.1.3:
              ansible_user: ""
              ansible_password: ""