---
all:
  children:
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_port: 5985
        ansible_winrm_transport: ntlm
        ansible_user: "" #REPLACE
        ansible_password: "" #REPLACE
        scripts_path: "" #REPLACE
        scripts_ansible_location: "/Windows-Scripts"
      # children:
      #   dc:
      #     vars:
      #       scored_services: "dnsio, ldapio"
      #       is_win_server: "true"
      #       server_type: "dc"
      #       is_server_core: "false"
      #     hosts:
      #       1.1.1.1:
      #   ca:
      #     vars:
      #       scored_services: "a"
      #       is_win_server: "true"
      #       server_type: "ca"
      #       is_server_core: "false"
      #     hosts:
      #       1.1.1.1:
      #   web:
      #     vars:
      #       scored_services: "httpio, httpsio"
      #       is_win_server: "true"
      #       server_type: "web"
      #       is_server_core: "false"
      #     hosts:
      #       1.1.1.1:
      #   smb:
      #     vars:
      #       scored_services: "smbio"
      #       is_win_server: "true"
      #       server_type: "smb"
      #       is_server_core: "false"
      #     hosts:
      #       1.1.1.1:
      #   winservclient:
      #     vars:
      #       scored_services: "a"
      #       is_win_server: "true"
      #       server_type: "null"
      #       is_server_core: "false"
      #     hosts:
      #       1.1.1.1:
      #       2.2.2.2:
      #   win10client:
      #     vars:
      #       scored_services: "a"
      #       is_win_server: "false"
      #       server_type: "null"
      #       is_server_core: "false"
      #     hosts:
      #       1.1.1.1:
